# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/nibao/Desktop/vivado/nbg_cpu_16/nbg_cpu_16.srcs/sources_1/ip/udiv/udiv.xci
# IP: The module: 'udiv' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/nibao/Desktop/vivado/nbg_cpu_16/nbg_cpu_16.gen/sources_1/ip/udiv/udiv_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'udiv'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/nibao/Desktop/vivado/nbg_cpu_16/nbg_cpu_16.srcs/sources_1/ip/udiv/udiv.xci
# IP: The module: 'udiv' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/nibao/Desktop/vivado/nbg_cpu_16/nbg_cpu_16.gen/sources_1/ip/udiv/udiv_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'udiv'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
