# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/nibao/Desktop/vivado/arm-v7m/nbg_cpu_thumb2/nbg_cpu_thumb2.srcs/sources_1/ip/blk_flash/blk_flash.xci
# IP: The module: 'blk_flash' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/nibao/Desktop/vivado/arm-v7m/nbg_cpu_thumb2/nbg_cpu_thumb2.gen/sources_1/ip/blk_flash/blk_flash_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_flash'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/nibao/Desktop/vivado/arm-v7m/nbg_cpu_thumb2/nbg_cpu_thumb2.srcs/sources_1/ip/blk_flash/blk_flash.xci
# IP: The module: 'blk_flash' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/nibao/Desktop/vivado/arm-v7m/nbg_cpu_thumb2/nbg_cpu_thumb2.gen/sources_1/ip/blk_flash/blk_flash_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_flash'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
