set_property PACKAGE_PIN U18 [get_ports sys_clk]
set_property PACKAGE_PIN N16 [get_ports sys_rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports sys_clk]
set_property IOSTANDARD LVCMOS33 [get_ports sys_rst_n]

set_property PACKAGE_PIN T19 [get_ports uart_rxd]
set_property PACKAGE_PIN J15 [get_ports uart_txd]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports uart_txd]

set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property PACKAGE_PIN H15 [get_ports {led[0]}]
set_property PACKAGE_PIN L15 [get_ports {led[1]}]
set_property PACKAGE_PIN J16 [get_ports {led[2]}]

set_property IOSTANDARD LVCMOS33 [get_ports {in_key[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {in_key[0]}]
set_property PACKAGE_PIN L14 [get_ports {in_key[0]}]
set_property PACKAGE_PIN K16 [get_ports {in_key[1]}]

set_property IOSTANDARD LVCMOS33 [get_ports {signal[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {signal[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {signal[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {signal[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {signal[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {signal[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {signal[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {signal[0]}]

set_property PACKAGE_PIN V17 [get_ports {signal[7]}]
set_property PACKAGE_PIN V18 [get_ports {signal[6]}]
set_property PACKAGE_PIN P15 [get_ports {signal[1]}]
set_property PACKAGE_PIN P16 [get_ports {signal[0]}]
set_property PACKAGE_PIN T17 [get_ports {signal[5]}]
set_property PACKAGE_PIN R18 [get_ports {signal[4]}]
set_property PACKAGE_PIN Y18 [get_ports {signal[3]}]
set_property PACKAGE_PIN Y19 [get_ports {signal[2]}]
