#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2024.1.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu Oct 24 11:34:00 CST 2024
# SW Build 5164865 on Thu Sep  5 14:36:28 MDT 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim TestBenchCPU_func_synth -key {Post-Synthesis:sim_1:Functional:TestBenchCPU} -tclbatch TestBenchCPU.tcl -view /home/nibaogang/vivado/nbg_cpu_16/TestBenchCPU_behav.wcfg -log simulate.log"
xsim TestBenchCPU_func_synth -key {Post-Synthesis:sim_1:Functional:TestBenchCPU} -tclbatch TestBenchCPU.tcl -view /home/nibaogang/vivado/nbg_cpu_16/TestBenchCPU_behav.wcfg -log simulate.log

